name: Running Solidity Unit Tests for Decent RA contracts


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run_sol_contracts_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        solc-version: [ 0.8.19 ]

    name: A job to run solidity unit tests on github actions CI
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run Solidity Unit Testing for ens-contracts Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/ens-contracts'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500

    - name: Run Solidity Unit Testing for RSA Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/RSA'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500

    - name: Run Solidity Unit Testing for ECDSA Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/Ecdsa'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500

    - name: Run Solidity Unit Testing for RLP Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/RLP'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500

    - name: Run Solidity Unit Testing for x509-forest-of-trust Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/x509-forest-of-trust'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500

    - name: Run Solidity Unit Testing for Decent Tests
      uses: EthereumRemix/sol-test@v1.1
      with:
        test-path: 'tests/Decent'
        compiler-version: ${{ matrix.solc-version }}
        optimize: true
        optimizer-runs: 500
